server:
  port: 8082

spring:
  application:
    name: song-service
  datasource:
    url: jdbc:postgresql://localhost:5433/song_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    open-in-view: false
