-- Schema for the Resource Service database.
-- Mirrors the JPA entity com.epam.microservices.resource.entity.ResourceEntity
-- (table "resources": IDENTITY primary key, MP3 payload stored as bytea).
-- The database itself is created by the POSTGRES_DB environment variable; this
-- script only creates tables.

CREATE TABLE resources (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data BYTEA NOT NULL
);
