server:
  port: 8081

spring:
  application:
    name: resource-service
  datasource:
    url: jdbc:postgresql://localhost:5432/resource_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

# Base URL of the Song Service used by the RestClient
song-service:
  base-url: http://localhost:8082
